name: Sequential Jobs

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 Step 1
        run: echooo "Running Job 1 Step 1"
      - name: Job 1 Step 2
        run: echooo "Running Job 1 Step 2"
      # Add more steps for Job 1 as needed

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Job 2 Step 1
        run: echo "Running Job 2 Step 1"
      - name: Job 2 Step 2
        run: echo "Running Job 2 Step 2"
      # Add more steps for Job 2 as needed
